"""comment on subdoctype

Revision ID: 1290ca6da86a
Revises: ff7188c160ad
Create Date: 2018-09-30 13:58:19.774592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1290ca6da86a'
down_revision = 'ff7188c160ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('subdoctype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'subdoctype', ['subdoctype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'subdoctype_id')
    # ### end Alembic commands ###
