"""subtype icon field

Revision ID: c8ec96a67a35
Revises: f0012057356a
Create Date: 2018-10-20 21:47:12.553063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ec96a67a35'
down_revision = 'f0012057356a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subdoctype', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subdoctype', 'icon')
    # ### end Alembic commands ###
