"""add included

Revision ID: f0012057356a
Revises: 690cc51b2377
Create Date: 2018-09-30 14:55:39.599675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0012057356a'
down_revision = '690cc51b2377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('included', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'included')
    # ### end Alembic commands ###
